AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  BinaryLambdaAPIGW:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Binary-Lambda-APIGW
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::644659814164:role/Lambda-Admin-Role'
      Runtime: nodejs12.x
      Timeout: 30
